/* generated by scripts/export_inferno_npcs.py -- do not edit */
#ifndef NPC_MODELS_INFERNO_H
#define NPC_MODELS_INFERNO_H

#include <stdint.h>
#include "npc_models.h"  /* for NpcModelMapping typedef */

static const NpcModelMapping NPC_MODEL_MAP_INFERNO_GEN[] = {
    {7691, 0xC1E0B, 7573, 7574, 7572},  /* Jal-Nib (nibbler) */
    {7692, 0xC1E0C, 7577, 7578, 7577},  /* Jal-MejRah (bat) */
    {7693, 0xC1E0D, 7586, 7581, 7587},  /* Jal-Ak (blob) */
    {7694, 0xC1E0E, 7586, 65535, 7587},  /* Jal-Ak-Rek-Ket (blob melee split) */
    {7695, 0xC1E0F, 7586, 65535, 7587},  /* Jal-Ak-Rek-Xil (blob range split) */
    {7696, 0xC1E10, 7586, 65535, 7587},  /* Jal-Ak-Rek-Mej (blob mage split) */
    {7697, 0xC1E11, 7595, 7597, 7596},  /* Jal-ImKot (meleer) */
    {7698, 0xC1E12, 7602, 7605, 7603},  /* Jal-Xil (ranger) */
    {7699, 0xC1E13, 7609, 7610, 7608},  /* Jal-Zek (mager) */
    {7700, 0xC1E14, 7589, 7593, 7588},  /* JalTok-Jad */
    {7701, 0xC1E15, 2636, 65535, 2634},  /* Yt-HurKot (jad healer) */
    {7706, 0xC1E1A, 7564, 7566, 65535},  /* TzKal-Zuk */
    {7707, 0xC1E1B, 7567, 65535, 7567},  /* Zuk shield */
    {7708, 0xC1E1C, 2867, 65535, 2863},  /* Jal-MejJak (zuk healer) */
};

/* inferno animation IDs */
#define INF_GEN_ANIM_NIBBLER_IDLE  7573
#define INF_GEN_ANIM_NIBBLER_ATTACK  7574
#define INF_GEN_ANIM_NIBBLER_WALK  7572
#define INF_GEN_ANIM_NIBBLER_DEFEND  7575
#define INF_GEN_ANIM_NIBBLER_DEATH  7576
#define INF_GEN_ANIM_BAT_IDLE  7577
#define INF_GEN_ANIM_BAT_ATTACK  7578
#define INF_GEN_ANIM_BAT_WALK  7577
#define INF_GEN_ANIM_BAT_DEFEND  7579
#define INF_GEN_ANIM_BAT_DEATH  7580
#define INF_GEN_ANIM_BLOB_IDLE  7586
#define INF_GEN_ANIM_BLOB_ATTACK  7581
#define INF_GEN_ANIM_BLOB_WALK  7587
#define INF_GEN_ANIM_BLOB_ATTACK_MELEE  7582
#define INF_GEN_ANIM_BLOB_ATTACK_RANGED  7583
#define INF_GEN_ANIM_BLOB_DEATH  7584
#define INF_GEN_ANIM_BLOB_DEFEND  7585
#define INF_GEN_ANIM_BLOB_MELEE_SPLIT_IDLE  7586
#define INF_GEN_ANIM_BLOB_MELEE_SPLIT_WALK  7587
#define INF_GEN_ANIM_BLOB_RANGE_SPLIT_IDLE  7586
#define INF_GEN_ANIM_BLOB_RANGE_SPLIT_WALK  7587
#define INF_GEN_ANIM_BLOB_MAGE_SPLIT_IDLE  7586
#define INF_GEN_ANIM_BLOB_MAGE_SPLIT_WALK  7587
#define INF_GEN_ANIM_MELEER_IDLE  7595
#define INF_GEN_ANIM_MELEER_ATTACK  7597
#define INF_GEN_ANIM_MELEER_WALK  7596
#define INF_GEN_ANIM_MELEER_DEFEND  7598
#define INF_GEN_ANIM_MELEER_DEATH  7599
#define INF_GEN_ANIM_MELEER_DIG_DOWN  7600
#define INF_GEN_ANIM_MELEER_DIG_UP  7601
#define INF_GEN_ANIM_RANGER_IDLE  7602
#define INF_GEN_ANIM_RANGER_ATTACK  7605
#define INF_GEN_ANIM_RANGER_WALK  7603
#define INF_GEN_ANIM_RANGER_ATTACK_MELEE  7604
#define INF_GEN_ANIM_RANGER_DEATH  7606
#define INF_GEN_ANIM_RANGER_DEFEND  7607
#define INF_GEN_ANIM_MAGER_IDLE  7609
#define INF_GEN_ANIM_MAGER_ATTACK  7610
#define INF_GEN_ANIM_MAGER_WALK  7608
#define INF_GEN_ANIM_MAGER_RESURRECT  7611
#define INF_GEN_ANIM_MAGER_ATTACK_MELEE  7612
#define INF_GEN_ANIM_MAGER_DEATH  7613
#define INF_GEN_ANIM_JALTOK_JAD_IDLE  7589
#define INF_GEN_ANIM_JALTOK_JAD_ATTACK  7593
#define INF_GEN_ANIM_JALTOK_JAD_WALK  7588
#define INF_GEN_ANIM_JALTOK_JAD_ATTACK_MELEE  7590
#define INF_GEN_ANIM_JALTOK_JAD_DEFEND  7591
#define INF_GEN_ANIM_JALTOK_JAD_ATTACK_MAGIC  7592
#define INF_GEN_ANIM_JALTOK_JAD_ATTACK_RANGED  7593
#define INF_GEN_ANIM_JALTOK_JAD_DEATH  7594
#define INF_GEN_ANIM_JAD_HEALER_IDLE  2636
#define INF_GEN_ANIM_JAD_HEALER_WALK  2634
#define INF_GEN_ANIM_TZKAL_ZUK_IDLE  7564
#define INF_GEN_ANIM_TZKAL_ZUK_ATTACK  7566
#define INF_GEN_ANIM_TZKAL_ZUK_DEATH  7562
#define INF_GEN_ANIM_TZKAL_ZUK_SPAWN  7563
#define INF_GEN_ANIM_TZKAL_ZUK_DEFEND  7565
#define INF_GEN_ANIM_ZUK_SHIELD_IDLE  7567
#define INF_GEN_ANIM_ZUK_SHIELD_WALK  7567
#define INF_GEN_ANIM_ZUK_SHIELD_HIT  7568
#define INF_GEN_ANIM_ZUK_SHIELD_DEATH  7569
#define INF_GEN_ANIM_ZUK_HEALER_IDLE  2867
#define INF_GEN_ANIM_ZUK_HEALER_WALK  2863

/* inferno spotanim GFX model + animation IDs */
#define INF_GEN_GFX_157_MODEL 3116  /* Jad magic hit */
#define INF_GEN_GFX_157_ANIM  693
#define INF_GEN_GFX_448_MODEL 9337  /* Jad magic projectile (front) */
#define INF_GEN_GFX_448_ANIM  2659
#define INF_GEN_GFX_449_MODEL 9338  /* Jad magic projectile (middle) */
#define INF_GEN_GFX_449_ANIM  2659
#define INF_GEN_GFX_450_MODEL 9339  /* Jad magic projectile (rear) */
#define INF_GEN_GFX_450_ANIM  2659
#define INF_GEN_GFX_451_MODEL 9342  /* Jad ranged projectile */
#define INF_GEN_GFX_451_ANIM  2660
#define INF_GEN_GFX_659_MODEL 14760  /* Tekton meteor splat */
#define INF_GEN_GFX_659_ANIM  3941
#define INF_GEN_GFX_660_MODEL 14759  /* Tekton meteor projectile */
#define INF_GEN_GFX_660_ANIM  3942
#define INF_GEN_GFX_1120_MODEL 26377  /* Dragon arrow projectile (twisted bow) */
#define INF_GEN_GFX_1120_ANIM  6622
#define INF_GEN_GFX_1374_MODEL 853342  /* Bat ranged projectile */
#define INF_GEN_GFX_1374_ANIM  660
#define INF_GEN_GFX_1375_MODEL 33006  /* Zuk magic projectile */
#define INF_GEN_GFX_1375_ANIM  7571
#define INF_GEN_GFX_1376_MODEL 33007  /* Zuk ranged projectile */
#define INF_GEN_GFX_1376_ANIM  7571
#define INF_GEN_GFX_1377_MODEL 33013  /* Ranger ranged projectile */
#define INF_GEN_GFX_1378_MODEL 33015  /* Ranger ranged hit */
#define INF_GEN_GFX_1378_ANIM  7615
#define INF_GEN_GFX_1379_MODEL 33016  /* Mager magic projectile */
#define INF_GEN_GFX_1379_ANIM  7614
#define INF_GEN_GFX_1380_MODEL 33008  /* Mager magic hit */
#define INF_GEN_GFX_1380_ANIM  7616
#define INF_GEN_GFX_1381_MODEL 33009  /* Zuk typeless hit (falling rocks?) */
#define INF_GEN_GFX_1381_ANIM  7616
#define INF_GEN_GFX_1382_MODEL 33017  /* Blob melee */
#define INF_GEN_GFX_1382_ANIM  7614
#define INF_GEN_GFX_1383_MODEL 853351  /* Blob ranged */
#define INF_GEN_GFX_1383_ANIM  366
#define INF_GEN_GFX_1384_MODEL 853352  /* Blob magic */
#define INF_GEN_GFX_1385_MODEL 853353  /* Healer magic attack */
#define INF_GEN_GFX_1385_ANIM  366

#endif /* NPC_MODELS_INFERNO_H */
