[base]
env_name = ants

[vec]
# 4096 % 32 agents == 0 and 4096 % (8192/64) == 0
total_agents = 4096
num_buffers = 4
num_threads = 16

[env]
num_agents = 32
width = 1280
height = 720
reward_food_pickup = 0.1
reward_delivery = 10.0

[policy]
hidden_size = 128
num_layers = 4

[train]
gpus = 1
total_timesteps = 100_000_000
learning_rate = 0.015
anneal_lr = 1
min_lr_ratio = 0
gamma = 0.995
gae_lambda = 0.90
replay_ratio = 1.0
clip_coef = 0.2
vf_coef = 2.0
vf_clip_coef = 0.2
max_grad_norm = 1.5
ent_coef = 0.001
momentum = 0.95
minibatch_size = 8192
horizon = 64
vtrace_rho_clip = 1.0
vtrace_c_clip = 1.0

[sweep]
metric = score

[sweep.train.total_timesteps]
distribution = log_normal
min = 5e7
max = 2e8
mean = 1e8
scale = time
