[base]
env_name = boids

[env]
num_envs = 64
num_boids = 64
; num_envs = 1
; num_boids = 1
margin_turn_factor = 0.0
centering_factor = 0.00
avoid_factor = 1.00
matching_factor = 1.00

[vec]
num_workers = 2
num_envs = 2
batch_size = auto

[train]
total_timesteps = 100_000_000
gamma = 0.95
learning_rate = 0.025
minibatch_size = 16384
; minibatch_size = 1

; [sweep]
; method = protein
; metric = episode_length

; [sweep.train.total_timesteps]
; distribution = log_normal
; min = 1e6
; max = 1e7
; mean = 5e6
; scale = 0.5

; [sweep.train.gamma]
; distribution = log_normal
; min = 0.9
; max = 0.999
; mean = 0.97

; [sweep.train.gae_lambda]
; distribution = log_normal
; min = 0.7
; max = 0.999
; mean = 0.95

; [sweep.train.learning_rate]
; distribution = log_normal
; min = 0.0001
; max = 0.001
; mean = 0.00025
; scale = 0.5

; [sweep.train.batch_size]
; min = 32768
; max = 131072
; mean = 65536
; scale = 0.5

; [sweep.train.minibatch_size]
; min = 512
; max = 2048
; mean = 1024
; scale = 0.5


