[base]
package = ocean
env_name = boids 
; policy_name = Boids
policy_name = Policy
rnn_name = Recurrent
; rnn_name = None

[env]
num_envs = 64
num_agents = 64
; num_envs = 1
; num_agents = 5
report_interval = 1
; margin_turn_factor = 1.0
; cohesion_factor = 0.0048
; separation_factor = 0.0128
; alignment_factor = 0.02
margin_turn_factor = 1.0
cohesion_factor = 1.0
separation_factor = 0.0
alignment_factor = 0.0

[vec]
total_agents = 4096
num_buffers = 8
num_threads = 8

[train]
total_timesteps = 100_000_000
gamma = 0.95
learning_rate = 0.025
minibatch_size = 16384
; minibatch_size = 1

[sweep]
method = Protein
metric = perf
sweep_only = margin_turn_factor, cohesion_factor, separation_factor, alignment_factor

[sweep.train.total_timesteps]
distribution = log_normal
min = 1e3
max = 1e7
scale = time

[sweep.env.margin_turn_factor]
distribution = log_normal
min = 0.01
max = 5.0
scale = auto

[sweep.env.cohesion_factor]
distribution = log_normal
min = 0.01
max = 1
scale = auto

[sweep.env.separation_factor]
distribution = log_normal
min = 0.01
max = 1
scale = auto

[sweep.env.alignment_factor]
distribution = log_normal
min = 0.01
max = 1
scale = auto
