[base]
env_name = None

# Multi-GPU (single GPU defaults)
rank = 0
world_size = 1
gpu_id = 0
nccl_id = 'None'
profile = False
checkpoint_dir = checkpoints
log_dir = logs
checkpoint_interval = 200
eval_episodes = 10000

# Epoch at which to capture CUDA graphs. -1 to disable.
cudagraphs = 10
seed = 73

# Whether to reset the LSTM state between epochs. We only use
# this for evals and have not tested it for training.
reset_state = True

[vec]
total_agents = 4096
num_buffers = 2
num_threads = 16

# Args used by your env's binding.c go here
[env]

[policy]
hidden_size = 128
num_layers = 4
expansion_factor = 1

[torch]
network = MinGRU
encoder = DefaultEncoder
decoder = DefaultDecoder

[train]
gpus = 1
seed = 42
total_timesteps = 10_000_000
learning_rate = 0.015
anneal_lr = 1
min_lr_ratio = 0.0
gamma = 0.995
gae_lambda = 0.90
replay_ratio = 1.0
clip_coef = 0.2
vf_coef = 2.0
vf_clip_coef = 0.2
max_grad_norm = 1.5
ent_coef = 0.001
beta1 = 0.95
beta2 = 0.999
eps = 1e-12
minibatch_size = 8192
horizon = 64
vtrace_rho_clip = 1.0
vtrace_c_clip = 1.0
prio_alpha = 0.8
prio_beta0 = 0.2

[sweep]
method = Protein 
metric = score
metric_distribution = linear
goal = maximize
max_suggestion_cost = 3600
max_runs = 1200
gpus = 0
downsample = 5
use_gpu = True
prune_pareto = True
early_stop_quantile = 0.3

[sweep.train.total_timesteps]
distribution = log_normal
min = 3e7
max = 1e11
scale = time

[sweep.policy.hidden_size]
distribution = uniform_pow2
min = 32
max = 1024
scale = auto

[sweep.policy.num_layers]
distribution = uniform
min = 1
max = 8
scale = auto

[sweep.vec.total_agents]
distribution = uniform_pow2
min = 256
max = 16384
scale = auto

[sweep.vec.num_buffers]
distribution = uniform
min = 1
max = 8
scale = auto

[sweep.train.horizon]
distribution = uniform_pow2
min = 8
max = 1024
scale = auto

[sweep.train.minibatch_size]
distribution = uniform_pow2
min = 4096
max = 65536
scale = auto

[sweep.train.learning_rate]
distribution = log_normal
min = 0.00001
max = 0.1
scale = 0.5

[sweep.train.ent_coef]
distribution = log_normal
min = 0.00001
max = 0.2
scale = auto

[sweep.train.gamma]
distribution = logit_normal
min = 0.8
max = 0.9999
scale = auto

[sweep.train.gae_lambda]
distribution = logit_normal
min = 0.2
#min = 0.6
max = 0.995
scale = auto

[sweep.train.vtrace_rho_clip]
distribution = uniform
min = 0.1
max = 5.0
scale = auto

[sweep.train.vtrace_c_clip]
distribution = uniform
min = 0.1
max = 5.0
scale = auto

[sweep.train.replay_ratio]
distribution = uniform
min = 0.25
max = 4.0
scale = auto

[sweep.train.clip_coef]
distribution = uniform
# Lower clip is sometimes better but less stable
min = 0.01
max = 1.0
scale = auto

# Optimal vf clip can be lower than 0.1,
# but this results in jank unstable runs
[sweep.train.vf_clip_coef]
distribution = uniform
min = 0.01
max = 5.0
scale = auto

[sweep.train.vf_coef]
distribution = uniform
min = 0.1
max = 5.0
scale = auto

[sweep.train.max_grad_norm]
distribution = uniform
min = 0.1
max = 5.0
scale = auto

[sweep.train.beta1]
distribution = logit_normal
min = 0.5
max = 0.999
scale = auto

[sweep.train.beta2]
distribution = logit_normal
min = 0.9
max = 0.99999
scale = auto

[sweep.train.eps]
distribution = log_normal
min = 1e-14
max = 1e-4
scale = auto

[sweep.train.prio_alpha]
distribution = uniform 
min = 0.0
max = 1.0
scale = auto

[sweep.train.prio_beta0]
distribution = uniform 
min = 0.0
max = 1.0
scale = auto
