[base]
env_name = drmario

[vec]
total_agents = 2048         
num_buffers = 4
num_threads = 4

[env]
n_rows = 16
n_cols = 8
n_init_viruses = 14

[policy]
hidden_size = 128            
num_layers = 1

[legacy]
torch_deterministic = 1
cpu_offload = 0
compile = 1
compile_fullgraph = 0

[train]
total_timesteps = 500_000_000
learning_rate = 0.001
gamma = 0.99
gae_lambda = 0.95
clip_coef = 0.2
vf_coef = 0.5
ent_coef = 0.01
minibatch_size = 16384       
horizon = 128
use_rnn = 0                  

#copied from Breakout
beta1 = 0.9
beta2 = 0.999
eps = 1e-8
max_grad_norm = 1.0
replay_ratio = 2
vtrace_rho_clip = 2.0
vtrace_c_clip = 2.0
prio_alpha = 0.6
prio_beta0 = 0.9