[base]
package = ocean
env_name = puffer_four_rooms
policy_name = Policy
rnn_name = Recurrent
#policy_name = FourRooms
#rnn_name = FourRoomsLSTM

[vec]
num_workers = 12
num_envs = 12

[env]
size = 27
num_envs = 256

[train]
device = mps
total_timesteps = 50_000_000
gamma = 0.99
learning_rate = 0.01
minibatch_size = 32768
clip_coef = 0.1
ent_coef = 0.01
vf_coef = 0.5
max_grad_norm = 0.5
