[base]
env_name = impulse_wars

max_suggestion_cost = 10_800

[policy]
hidden_size = 512
cnn_channels = 64

# These must match what's set in env below
continuous = False
num_drones = 2
is_training = True

[vec]
num_envs = 4
#num_workers = 4
#batch_size = 4

[env]
num_envs = 1024
num_drones = 2
num_agents = 1
enable_teams = False
sitting_duck = False
continuous = False
is_training = True

[train]
total_timesteps = 1_000_000_000
checkpoint_interval = 250

learning_rate = 0.005

compile = False
compile_mode = reduce-overhead
compile_fullgraph = False


[sweep]
downsample = 10
max_cost = 900

[sweep.env.num_envs]
distribution = uniform_pow2
min = 1
max = 1024
mean = 128
scale = auto

# reward parameters
[sweep.env.reward_win]
distribution = uniform
min = 0.0
mean = 2.0
max = 5.0
scale = auto

[sweep.env.reward_self_kill]
distribution = uniform
min = -3.0
mean = -1.0
max = 0.0
scale = auto

[sweep.env.reward_enemy_death]
distribution = uniform
min = 0.0
mean = 1.0
max = 3.0
scale = auto

[sweep.env.reward_kill]
distribution = uniform
min = 0.0
mean = 1.0
max = 3.0
scale = auto

[sweep.env.reward_death]
distribution = uniform
min = -1.0
mean = -0.25
max = 0.0
scale = auto

[sweep.env.reward_energy_emptied]
distribution = uniform
min = -2.0
mean = -0.75
max = 0.0
scale = auto

[sweep.env.reward_weapon_pickup]
distribution = uniform
min = 0.0
mean = 0.5
max = 3.0
scale = auto

[sweep.env.reward_shield_break]
distribution = uniform
min = 0.0
mean = 0.5
max = 3.0
scale = auto

[sweep.env.reward_shot_hit_coef]
distribution = log_normal
min = 0.0005
mean = 0.005
max = 0.05
scale = auto

[sweep.env.reward_explosion_hit_coef]
distribution = log_normal
min = 0.0005
mean = 0.005
max = 0.05
scale = auto

# hyperparameters
[sweep.train.total_timesteps]
distribution = log_normal
min = 250_000_000
max = 1_500_000_000
mean = 500_000_000
scale = time

[sweep.train.batch_size]
distribution = uniform_pow2
min = 65_536
max = 1_048_576
mean = 262_144
scale = auto

[sweep.train.horizon]
distribution = uniform_pow2
min = 64
max = 256
mean = 128
scale = auto

