[base]
env_name = impulse_wars

[policy]
hidden_size = 512
num_layers = 2

[vec]
# 4096 % num_agents (1) == 0 and 4096 % (8192/64) == 0
total_agents = 4096
num_buffers = 4
num_threads = 4

[env]
num_drones = 2
num_agents = 1
map_idx = -1
seed = 1
enable_teams = 0
sitting_duck = 0
continuous = 0
is_training = 1
reward_win = 2.0
reward_self_kill = -1.0
reward_enemy_death = 1.0
reward_enemy_kill = 1.0
reward_death = 0.0
reward_energy_emptied = -0.75
reward_weapon_pickup = 0.5
reward_shield_break = 0.5
reward_shot_hit_coef = 0.005
reward_explosion_hit_coef = 0.005

[train]
total_timesteps = 60_000_000
learning_rate = 0.005

[sweep]
downsample = 10
max_cost = 900

[sweep.env.reward_win]
distribution = uniform
min = 0.0
mean = 2.0
max = 5.0
scale = auto

[sweep.env.reward_self_kill]
distribution = uniform
min = -3.0
mean = -1.0
max = 0.0
scale = auto

[sweep.env.reward_enemy_death]
distribution = uniform
min = 0.0
mean = 1.0
max = 3.0
scale = auto

[sweep.env.reward_enemy_kill]
distribution = uniform
min = 0.0
mean = 1.0
max = 3.0
scale = auto

[sweep.env.reward_death]
distribution = uniform
min = -1.0
mean = -0.25
max = 0.0
scale = auto

[sweep.env.reward_energy_emptied]
distribution = uniform
min = -2.0
mean = -0.75
max = 0.0
scale = auto

[sweep.env.reward_weapon_pickup]
distribution = uniform
min = 0.0
mean = 0.5
max = 3.0
scale = auto

[sweep.env.reward_shield_break]
distribution = uniform
min = 0.0
mean = 0.5
max = 3.0
scale = auto

[sweep.env.reward_shot_hit_coef]
distribution = log_normal
min = 0.0005
mean = 0.005
max = 0.05
scale = auto

[sweep.env.reward_explosion_hit_coef]
distribution = log_normal
min = 0.0005
mean = 0.005
max = 0.05
scale = auto

[sweep.train.total_timesteps]
distribution = log_normal
min = 50_000_000
max = 250_000_000
mean = 80_000_000
scale = time
