[base]
package = morph
env_name = morph
vec = native
policy_name = Policy
# rnn_name = Recurrent

[policy]
demo_size = 358
hidden_size = 1024

[rnn]
input_size = 1024
hidden_size = 1024

[env]
motion_file = "resources/morph/dfaust_one_leg_jump.pkl"
has_self_collision = True
num_envs = 2048
headless = True
# num_envs = 32

[train]
seed = 1
torch_deterministic = True
device = cuda

cpu_offload = False
compile = False
norm_adv = True
target_kl = None

total_timesteps = 5_000_000_000
eval_timesteps = 655_000

num_workers = 1
num_envs = 1
batch_size = 65536
minibatch_size = 16384
# batch_size = 1024
# minibatch_size = 256

disc_coef = 5.0

update_epochs = 4
bptt_horizon = 8
anneal_lr = False
gae_lambda = 0.95
gamma = 0.99
clip_coef = 0.5
clip_vloss = True
vf_coef = 1.0
vf_clip_coef = 0.5
max_grad_norm = 1.0
ent_coef = 0.0001
learning_rate = 0.000015
checkpoint_interval = 1000


[sweep]
method = bayes
name = sweep

[sweep.metric]
goal = maximize
name = environment/episode_return

[sweep.parameters.train.parameters.total_timesteps]
distribution = log_uniform_values
min = 10_000_000
max = 200_000_000

[sweep.parameters.train.parameters.learning_rate]
distribution = log_uniform_values
min = 1e-5
max = 1e-1

[sweep.parameters.train.parameters.gamma]
distribution = uniform
min = 0.0
max = 1.0

[sweep.parameters.train.parameters.gae_lambda]
distribution = uniform
min = 0.0
max = 1.0

[sweep.parameters.train.parameters.vf_coef]
distribution = uniform
min = 0.0
max = 5.0

[sweep.parameters.train.parameters.max_grad_norm]
distribution = uniform
min = 0.0
max = 20.0

[sweep.parameters.train.parameters.bptt_horizon]
values = [4, 8, 16]
