[base]
package = morph
env_name = morph
vec = native
policy_name = Policy
rnn_name = Recurrent

[policy]
demo_size = 358
hidden_size = 512

[rnn]
input_size = 512
hidden_size = 512

[env]
motion_file = "resources/morph/dfaust_one_leg_jump.pkl"
has_self_collision = True
num_envs = 4096
headless = True
rew_power_coef = 0.001

[train]
seed = 1
torch_deterministic = True
device = cuda

cpu_offload = False
compile = False
norm_adv = True
target_kl = None

total_timesteps = 5_000_000_000
eval_timesteps = 1_310_000

data_dir = experiments
checkpoint_interval = 1000
motion_resample_interval = 200

num_workers = 1
num_envs = 1
batch_size = 131072
minibatch_size = 8192
# batch_size = 1024
# minibatch_size = 256

learning_rate = 0.0002
# Keep this for other envs
anneal_lr = False
# For morph, use exp decay exp(-decay_rate * steps)
lr_decay_rate = 2e-3
# With the decay floor, the LR does not decay below LR * decay_floor
lr_decay_floor = 0.05

update_epochs = 3
bptt_horizon = 8
gae_lambda = 0.75
gamma = 0.91
clip_coef = 0.025
clip_vloss = True
vf_coef = 0.5
vf_clip_coef = 0.2
max_grad_norm = 0.5
ent_coef = 0.0

# Not used yet
disc_coef = 5.0

[sweep]
method = bayes
name = sweep

[sweep.metric]
goal = maximize
# name = environment/episode_return
name = eval/success_rate

[sweep.parameters.train.parameters.total_timesteps]
distribution = log_uniform_values
min = 20_000_000
max = 80_000_000

[sweep.parameters.train.parameters.learning_rate]
distribution = log_uniform_values
min = 1e-5
max = 1e-3

[sweep.parameters.train.parameters.gamma]
distribution = uniform
min = 0.0
max = 1.0

; [sweep.parameters.train.parameters.gae_lambda]
; distribution = uniform
; min = 0.0
; max = 1.0

[sweep.parameters.train.parameters.clip_coef]
distribution = uniform
min = 0.0
max = 1.0

; [sweep.parameters.train.parameters.vf_coef]
; distribution = uniform
; min = 0.0
; max = 2.0

; [sweep.parameters.train.parameters.vf_clip_coef]
; distribution = uniform
; min = 0.0
; max = 1.0

; [sweep.parameters.train.parameters.update_epochs]
; distribution = int_uniform
; min = 1
; max = 6

; [sweep.parameters.train.parameters.minibatch_size]
; distribution = log_uniform_values
; min = 8192
; max = 65536

; [sweep.parameters.env.parameters.rew_power_coef]
; distribution = log_uniform_values
; min = 1e-4
; max = 1e-2
