[base]
package = morph
env_name = morph-render
vec = native
policy_name = PHCPolicy
# rnn_name = Recurrent

[policy]
hidden_size = 512

[rnn]
input_size = 512
hidden_size = 512

[env]
motion_file = "amass_train_take6_upright.pkl"
# motion_file = "amass_train_11k_upright.pkl"
has_self_collision = True
headless = False
num_envs = 32

[train]
seed = 1
torch_deterministic = True
device = cuda

cpu_offload = False
compile = False
norm_adv = True
target_kl = None

total_timesteps = 5_000_000_000
eval_timesteps = 1_310_000

num_workers = 1
num_envs = 1
batch_size = 1024
minibatch_size = 256

disc_coef = 5.0

update_epochs = 4
bptt_horizon = 8
anneal_lr = False
gae_lambda = 0.95
gamma = 0.99
clip_coef = 0.5
clip_vloss = True
vf_coef = 1.0
vf_clip_coef = 0.5
max_grad_norm = 1.0
ent_coef = 0.00001
learning_rate = 0.000015
checkpoint_interval = 1000
