[base]
package = morph
env_name = morph-render
vec = native
policy_name = PHCPolicy
# rnn_name = Recurrent

[policy]
hidden_size = 512

[rnn]
input_size = 512
hidden_size = 512

[env]
motion_file = "resources/morph/dfaust_one_leg_jump.pkl"
has_self_collision = True
headless = False
num_envs = 32
termination_distance = 10.0
kp_scale = 1.0
kd_scale = 1.0

[train]
seed = 1
torch_deterministic = True
device = cuda

cpu_offload = False
compile = False
norm_adv = True
target_kl = None

total_timesteps = 5_000_000_000
eval_timesteps = 1_310_000

num_workers = 1
num_envs = 1
batch_size = 1024
minibatch_size = 256

learning_rate = 0.0001
# Keep this for other envs
anneal_lr = False
# For morph, use exp decay exp(-decay_rate * steps)
lr_decay_rate = 1.5e-4
# With the decay floor, the LR does not decay below LR * decay_floor
lr_decay_floor = 0.2

update_epochs = 4
bptt_horizon = 8
gae_lambda = 0.2
gamma = 0.98
clip_coef = 0.01
vf_coef = 1.2
clip_vloss = True
vf_clip_coef = 0.2
max_grad_norm = 10.0
ent_coef = 0.0
disc_coef = 5.0
bound_coef = 10.0
l2_reg_coef = 0.0
