[base]
env_name = nethack

[vec]
total_agents = 512
num_buffers = 4
num_threads = 32

[env]
gold_coef = 0.0530697852
score_coef = 0.00148907036
exp_coef = 0.0912783295
descent_coef = 1.0
floor_coef = 0.126026332
xp_coef = 1.0
scout_coef = 0.00686222408
death_penalty = -0.472198129

# flags
# 1 removes the verb from the action space
mask_search20 = 0
mask_run = 0
# 1 = random role/race/gender/align per reset (challenge protocol)
multi_role = 1

[policy]
hidden_size = 1024
num_layers = 4

[train]
total_timesteps = 1_000_000_000
minibatch_size = 4096
horizon = 512
learning_rate = 0.000724339974
momentum = 0.981004834
verb_eps = 0.005
verb_eps_anneal_start = 0.4
verb_eps_anneal_end = 1.0
gamma = 0.999207735
gae_lambda = 0.484387815
replay_ratio = 1.78021395
clip_coef = 0.324817508
vf_coef = 0.399207175
vf_clip_coef = 1.60136652
max_grad_norm = 0.100000001
ent_coef = 0.00656300783

[sweep]
metric = score

[sweep.train.total_timesteps]
distribution = log_normal
min = 2e8
max = 1e9
scale = time

[sweep.env.exp_coef]
distribution = log_normal
min = 0.001
max = 0.1
scale = auto

[sweep.env.score_coef]
distribution = log_normal
min = 0.001
max = 0.1
scale = auto

[sweep.env.gold_coef]
distribution = log_normal
min = 0.001
max = 0.1
scale = auto

[sweep.env.descent_coef]
distribution = uniform
min = 0.0
max = 1.0
scale = auto

[sweep.env.xp_coef]
distribution = uniform
min = 0.0
max = 1.0
scale = auto

[sweep.env.scout_coef]
distribution = log_normal
min = 0.0001
max = 0.1
scale = auto

[sweep.env.death_penalty]
distribution = uniform
min = -1.0
max = 0.0
scale = auto

[sweep.train.verb_eps]
distribution = log_normal
min = 0.0005
max = 0.02
scale = auto

[sweep.train.verb_eps_anneal_start]
distribution = uniform
min = 0.2
max = 0.8
scale = auto

[sweep.env.floor_coef]
distribution = uniform
min = 0.0
max = 1.0
scale = auto
