[base]
env_name = nmmo3

[vec]
total_agents = 4096
num_buffers = 4
num_threads = 4

[env]
num_agents = 1024
width = 512
height = 512
num_enemies = 2048
num_resources = 2048
num_weapons = 1024
num_gems = 512
tiers = 5
levels = 40
teleportitis_prob = 0.001
enemy_respawn_ticks = 2
item_respawn_ticks = 100
x_window = 7
y_window = 5
reward_combat_level = 0.689959466
reward_prof_level = 0.922388434
reward_item_level = 0.587256789
reward_market = 0.0
reward_death = -0.127605617
clear_stale_entities = 1

[policy]
hidden_size = 512
num_layers = 6

[train]
# Sweep 0190 (14.60 score, 23 min / 1.19B). num_layers sampled 6.62 -> 6.
total_timesteps = 1_200_000_000
checkpoint_interval = 200
learning_rate = 0.0048671416
anneal_lr = 1
min_lr_ratio = 0
gamma = 0.999558508
gae_lambda = 0.427651882
replay_ratio = 1.43214154
clip_coef = 0.142623141
vf_coef = 2.5599246
vf_clip_coef = 0.583189428
max_grad_norm = 1.23915112
ent_coef = 0.00163615437
momentum = 0.859445274
minibatch_size = 32768
horizon = 32

[sweep]
downsample = 50

[sweep.train.total_timesteps]
distribution = log_normal
min = 2e9
max = 4e9
scale = time

[sweep.vec.total_agents]
distribution = uniform_pow2
min = 1024
max = 16384
scale = auto
