[base]
env_name = pysquared

# Set up to match our C version defaults for speed comparison
[vec]
num_envs = 8192
num_workers = 2

[train]
total_timesteps = 20_000_000
gamma = 0.95
learning_rate = 0.05
minibatch_size = 32768
