[base]
env_name = soccer
wandb_project = None
checkpoint_interval = 5000

[vec]
total_agents = 600
num_buffers = 1
num_threads = 1
num_policies = 2
hist_policy_percent = 0.1
hist_policy_hidden_size = 256
hist_policy_num_layers = 4

[env]
num_agents = 2
max_steps = 3000
render = 0

accel = 120
turn_rate = 2.6
player_friction = 0.65
ball_friction = 0.05
restitution = 0.92
dt = 0.05
frameskip = 1

reward_goal = 0.75
reward_ball_progress = 0.141525581
reward_timeout_ball_position = 0.25
; global_agents must match vec.total_agents
global_agents = 600
timeout_ball_reward_anneal_start = 125_000_000
timeout_ball_reward_anneal_end = 250_000_000

[selfplay]
enabled = 1
max_size = 100
seed = 42
opp_timeout_steps = 100_000_000
eval_pool_size = 8
eval_games = 4096

[policy]
hidden_size = 256
num_layers = 4
expansion_factor = 1

[train]
gpus = 1
seed = 42
total_timesteps = 1_000_000_000
learning_rate = 0.000355889278
anneal_lr = 1
min_lr_ratio = 0
gamma = 0.998999298
gae_lambda = 0.969999433
replay_ratio = 1.43177086
clip_coef = 0.0778364613
vf_coef = 0.999999464
vf_clip_coef = 0.999999464
max_grad_norm = 0.699999392
ent_coef = 0.00200116425
momentum = 0.94999969
minibatch_size = 4096
horizon = 64
vtrace_rho_clip = 1
vtrace_c_clip = 1
prio_alpha = 0.6
prio_beta0 = 0.4

[sweep]
metric = score
metric_distribution = linear
goal = maximize
max_runs = 1000
max_suggestion_cost = 5400
gpus = 1
use_gpu = False

[sweep.train.total_timesteps]
distribution = log_normal
min = 500_000_000
max = 1_000_000_000
scale = time

[sweep.train.learning_rate]
distribution = log_normal
min = 0.0001
max = 0.0015
scale = 0.5

[sweep.train.ent_coef]
distribution = log_normal
min = 0.0005
max = 0.005
scale = 0.5

[sweep.train.replay_ratio]
distribution = uniform
min = 0.5
max = 2.4
scale = auto

[sweep.train.clip_coef]
distribution = uniform
min = 0.05
max = 0.2
scale = auto

[sweep.env.reward_goal]
distribution = uniform
min = 0.5
max = 1.0
scale = auto

[sweep.env.reward_ball_progress]
distribution = uniform
min = 0.0
max = 0.5
scale = auto
