[base]
env_name = terraform

[vec]
total_agents = 2048
num_buffers = 4.40297
num_threads = 2

[env]
num_envs = 1024
num_agents = 1
size = 64
reset_frequency = 1024
reward_scale = 0.0907157

[policy]
hidden_size = 512
num_layers = 5.46436
expansion_factor = 1

[rnn]
input_size = 256
hidden_size = 256

[train]
gpus = 1
seed = 42
total_timesteps = 234873016
learning_rate = 0.00551772
anneal_lr = 1
min_lr_ratio = 0
gamma = 0.89571
gae_lambda = 0.2
replay_ratio = 1.78841
clip_coef = 0.01
vf_coef = 5
vf_clip_coef = 1.19287
max_grad_norm = 2.21317
ent_coef = 0.0079761
beta1 = 0.965804
beta2 = 0.999389
eps = 0.0001
minibatch_size = 16384
horizon = 256
vtrace_rho_clip = 4.24942
vtrace_c_clip = 2.12831
prio_alpha = 0.451327
prio_beta0 = 0.676252
adam_beta1 = 0.879231
adam_beta2 = 0.998046
adam_eps = 6.00018e-06
use_rnn = 1

[sweep.train.total_timesteps]
distribution = log_normal
min = 2e8
max = 6e8
mean = 4e8
scale = time

#[sweep.env.reset_frequency]
#distribution = int_uniform
#min = 1024
#max = 16384
#mean = 8192
#scale = auto

[sweep.env.reward_scale]
distribution = log_normal
min = 0.01
max = 1
mean = 0.5
scale = auto
