[base]
package = ocean
env_name = puffer_artillery
policy_name = Policy
rnn_name = Recurrent

[vec]
num_envs = 8

[env]
num_envs = 1024
width = 1280
height = 720
debug = 0
dist_fade = 0.3
frameskip = 1
ftmp1 = 100.0
ftmp2 = 50.0
ftmp3 = 0.22
ftmp4 = 0.1
method = -1
miss_penalty = -0.2
min_aim_angle = 0.56
max_aim_angle = 1.56
max_reward = 1.00
max_reward_dist = 30
max_dist0 = 250
max_score = 1.0
out_bounds_penalty = -0.1
target_min_x = 600
target_max_x = 1230
target_min_y = 300
target_max_y = 670
turn_penalty = -0.03
turn_penalty_delay = 75
turn_penalty_ramp = 0.015
render_many = 0
rng = 7
same_runs = 1
vm = 150

[policy]
hidden_size = 128

[rnn]
input_size = 128
hidden_size = 128

[train]
adam_beta1 = 0.9603485277769915
adam_beta2 = 0.9676992387435311
adam_eps = 9.4852806860935e-08
batch_size = auto
bptt_horizon = 64
clip_coef = 0.048815198297704664
ent_coef = 0.017849546840832453
gae_lambda = 0.96
gamma = 0.9840496436204362
learning_rate = 0.10394745361108008
max_grad_norm = 1.1472582280302297
#max_minibatch_size = 32768
#min_minibatch_size = 32768
minibatch_size = 16384 #16384 32768
prio_alpha = 0.8573365561813164
prio_beta0 = 0.9145256572446854
total_timesteps = 100_000_000
vf_clip_coef = 0.1921803059597499
vf_coef = 0.9716703254857812
vtrace_c_clip = 1.3091691449874727
vtrace_rho_clip = 1.5308269023087249

[sweep]
method = Protein
metric = acc1000
goal = maximize
downsample = 10

#[sweep.env.sigma]
#distribution = uniform
#min = 10
#max = 75
#mean = 30
#scale = auto

#[sweep.env.sigma_decay]
#distribution = uniform
#min = 0.0
#max = 0.1
#mean = 0.0001
#scale = auto

#[sweep.train.total_timesteps]
#distribution = log_normal
#min = 90_000_000
#max = 100_000_000
#mean = 90_500_000
#scale = auto

[sweep.train.learning_rate]
distribution = log_normal
min = 0.05
mean = 0.065
max = 0.08
scale = 0.5

#[sweep.env.frameskip]
#distribution = categorical
#values = 1, 2, 4, 8

[sweep.env.max_dist0]
distribution = uniform
min = 100.0
max = 750.0
mean = 500.0
scale = auto

[sweep.env.dist_fade]
distribution = uniform
min = 0.0001
max = 1.0
mean = 0.01
scale = auto

[sweep.env.same_runs]
distribution = uniform
min =1
max = 50
mean = 10
scale = auto

[sweep.env.max_reward_dist]
distribution = uniform
min = 20
max = 150
mean = 50
scale = auto

#[sweep.env.max_reward]
#distribution = uniform
#min = 0.05
#max = 1.0
#mean = 0.75
#scale = auto

[sweep.env.turn_penalty]
distribution = uniform
min = -0.1
max = -0.003
mean = -0.01
scale = auto

[sweep.env.turn_penalty_delay]
distribution = uniform
min = 50
max = 100
mean = 75
scale = auto

[sweep.env.turn_penalty_ramp]
distribution = uniform
min = 0.01
max = 0.05
mean = 0.015
scale = auto

[sweep.env.miss_penalty]
distribution = uniform
min = -1.0
max = -0.1
mean = -0.5
scale = auto

#[sweep.train.vtrace_rho_clip]
#distribution = uniform
#min = 1.0
#max = 5.0
#mean = 1.5
#scale = auto

#[sweep.train.max_grad_norm]
#distribution = uniform
#min = 1.0
#mean = 1.25
#max = 5.0
#scale = auto

#[sweep.train.vf_coef]
#distribution = uniform
#min = 0.0
#max = 1.0
#mean = 1.8
#scale = auto

#[sweep.train.gae_lambda]
#distribution = logit_normal
#min = 0.96
#mean = 0.984
#max = 0.9995
#scale = auto

#[sweep.train.vtrace_c_clip]
#distribution = uniform
#min = 0.0
#max = 4.0
#mean = 1.0
#scale = auto

#[sweep.train.minibatch_size]
#distribution = uniform_pow2
#min = 8192
#max = 32768
#mean = 16384
#scale = auto

#[sweep.train.ent_coef]
#distribution = log_normal
#min = 0.00001
#mean = 0.005
#max = 0.05
#scale = auto
