[base]
package = ocean
env_name = puffer_artillery3d
policy_name = Policy
rnn_name = Recurrent

[vec]
num_envs = 8

[env]
num_envs = 1024
debug = 0

dist_fade = 0.710072806997305
max_dist0 = 234.64824369842947
max_reward = 1.00
max_reward_dist = 27.03551509695456
miss_penalty = -0.25940170475653745
out_bounds_penalty = -0.01
target_size = 15
turn_penalty = -0.003
turn_penalty_delay = 82.72658483710038
turn_penalty_ramp = 0.014982041505364934
rng = 7
same_runs = 1

[policy]
hidden_size = 128

[rnn]
input_size = 128
hidden_size = 128

[train]
adam_beta1 = 0.9603485277769915
adam_beta2 = 0.9676992387435311
adam_eps = 9.4852806860935e-08
batch_size = auto
bptt_horizon = 64
clip_coef = 0.048815198297704664
ent_coef = 0.049999999999999996
gae_lambda = 0.95
gamma = 0.9840496436204362
learning_rate = 0.005
max_grad_norm = 2.589981415830053
#max_minibatch_size = 32768
#min_minibatch_size = 32768
minibatch_size = 32768 #16384 32768
prio_alpha = 0.8573365561813164
prio_beta0 = 0.9145256572446854
total_timesteps = 400_000_000
vf_clip_coef = 0.1921803059597499
vf_coef = 0.8111721600187421
vtrace_c_clip = 2.13335526866267
vtrace_rho_clip = 2.0368704261583224

[sweep]
method = Protein
metric = acc1000
goal = maximize
downsample = 10

#[sweep.train.total_timesteps]
#distribution = log_normal
#min = 90_000_000
#max = 100_000_000
#mean = 90_500_000
#scale = auto

#[sweep.train.learning_rate]
#distribution = log_normal
#min = 0.005
#mean = 0.0065
#max = 0.01
#scale = 0.5

#[sweep.env.frameskip]
#distribution = categorical
#values = 1, 2, 4, 8

[sweep.env.max_dist0]
distribution = uniform
min = 25.0
max = 250.0
mean = 200.0
scale = auto

[sweep.env.dist_fade]
distribution = uniform
min = 0.01
max = 1.0
mean = 0.36
scale = auto

#[sweep.env.same_runs]
#distribution = uniform
#min =1
#max = 50
#mean = 10
#scale = auto

[sweep.env.max_reward_dist]
distribution = uniform
min = 5
max = 50
mean = 10
scale = auto

[sweep.env.turn_penalty]
distribution = uniform
min = -0.01
max = -0.003
mean = -0.003
scale = auto

[sweep.env.turn_penalty_delay]
distribution = uniform
min = 50
max = 100
mean = 64
scale = auto

[sweep.env.turn_penalty_ramp]
distribution = uniform
min = 0.01
max = 0.02
mean = 0.023
scale = auto

[sweep.env.miss_penalty]
distribution = uniform
min = -1.0
max = -0.1
mean = -0.1
scale = auto

[sweep.train.adam_beta1]
distribution = logit_normal
min = 0.5
mean = 0.9239595133885746
max = 0.999
scale = auto

[sweep.train.adam_beta2]
distribution = logit_normal
min = 0.9
mean = 0.9995517967224462
max = 0.99999
scale = auto

[sweep.train.adam_eps]
distribution = log_normal
min = 1e-14
mean = 4.755400969633809e-10
max = 1e-4
scale = auto

[sweep.train.bptt_horizon]
distribution = uniform_pow2
min = 16
max = 64
mean = 64
scale = auto

[sweep.train.clip_coef]
distribution = uniform
min = 0.2
max = 0.7
mean = 0.3578157495708193
scale = auto

[sweep.train.ent_coef]
distribution = log_normal
min = 0.00001
mean = 0.009646058417032767
max = 0.03
scale = auto

[sweep.train.gae_lambda]
distribution = logit_normal
min = 0.6
mean = 0.9855679129280063
max = 0.995
scale = auto

[sweep.train.gamma]
distribution = logit_normal
min = 0.8
mean = 0.9995813160924099
max = 0.9999
scale = auto

[sweep.train.learning_rate]
distribution = log_normal
min = 0.00001
mean = 0.024999999999999994
max = 0.025
scale = auto

[sweep.train.max_grad_norm]
distribution = uniform
min = 0.0
mean = 4.596577484524367
max = 5.0
scale = auto

#[sweep.train.minibatch_size]
#distribution = uniform_pow2
#min = 8192
#max = 65536
#mean = 32768
#scale = auto

[sweep.train.prio_alpha]
distribution = logit_normal
min = 0.95
mean = 0.977084336136257
max = 0.99
scale = auto

[sweep.train.prio_beta0]
distribution = logit_normal
min = 0.1
mean = 0.2962685317679963
max = 0.99
scale = auto

[sweep.train.vf_clip_coef]
distribution = uniform
min = 0.3
max = 1.0
mean = 0.3372181149959871
scale = auto

[sweep.train.vf_coef]
distribution = uniform
min = 4.0
max = 5.0
mean = 5.0
scale = auto

[sweep.train.vtrace_c_clip]
distribution = uniform
min = 2.0
max = 3.0
mean = 3.1407471151530455
scale = auto

[sweep.train.vtrace_rho_clip]
distribution = uniform
min = 1.0
max = 3.0
mean = 1.79801075035328
scale = auto
