[base]
package = ocean
env_name = puffer_artillery3d
policy_name = Policy
rnn_name = Recurrent

[vec]
num_envs = 8

[env]
num_envs = 1024
debug = 0

dist_fade = 0.7493789405520497
max_dist0 = 127.50246246114087
max_reward = 1.00
max_reward_dist = 23.620013496047616
miss_penalty = -0.1858434974084412
out_bounds_penalty = -0.01
target_size = 15
turn_penalty = -0.003
turn_penalty_delay = 72.37761171826367
turn_penalty_ramp = 0.02
rng = 7
same_runs = 1

[policy]
hidden_size = 128

[rnn]
input_size = 128
hidden_size = 128

[train]
adam_beta1 = 0.861073582587165
adam_beta2 = 0.99999
adam_eps = 4.848310365732972e-12
batch_size = auto
bptt_horizon = 64
clip_coef = 0.3402139435986118
ent_coef = 0.030000000000000013
gae_lambda = 0.9850334966277443
gamma = 0.9993197059145731
learning_rate = 0.024999999999999994
max_grad_norm = 4.488781435328298
#max_minibatch_size = 32768
#min_minibatch_size = 32768
minibatch_size = 32768 #16384 32768
prio_alpha = 0.981927524144426
prio_beta0 = 0.09999999999999998
total_timesteps = 400_000_000
vf_clip_coef = 0.3
vf_coef = 4.865415765982929
vtrace_c_clip = 2.6829701985053878
vtrace_rho_clip = 2.1589447317754478

[sweep]
method = Protein
metric = acc1000
goal = maximize
downsample = 10

#[sweep.train.total_timesteps]
#distribution = log_normal
#min = 90_000_000
#max = 100_000_000
#mean = 90_500_000
#scale = auto

#[sweep.train.learning_rate]
#distribution = log_normal
#min = 0.005
#mean = 0.0065
#max = 0.01
#scale = 0.5

#[sweep.env.frameskip]
#distribution = categorical
#values = 1, 2, 4, 8

[sweep.env.dist_fade]
distribution = uniform
min = 0.01
max = 1.0
mean = 0.7493789405520497
scale = auto

[sweep.env.max_dist0]
distribution = uniform
min = 25.0
max = 250.0
mean = 127.50246246114087
scale = auto

#[sweep.env.same_runs]
#distribution = uniform
#min =1
#max = 50
#mean = 10
#scale = auto

[sweep.env.max_reward_dist]
distribution = uniform
min = 5
max = 50
mean = 23.620013496047616
scale = auto

[sweep.env.miss_penalty]
distribution = uniform
min = -1.0
max = -0.1
mean = -0.1858434974084412
scale = auto

[sweep.env.turn_penalty]
distribution = uniform
min = -0.01
max = -0.002
mean = -0.003
scale = auto

[sweep.env.turn_penalty_delay]
distribution = uniform
min = 50
max = 100
mean = 72.37761171826367
scale = auto

[sweep.env.turn_penalty_ramp]
distribution = uniform
min = 0.01
max = 0.05
mean = 0.02
scale = auto

[sweep.train.adam_beta1]
distribution = logit_normal
min = 0.5
mean = 0.861073582587165
max = 0.999
scale = auto

[sweep.train.adam_beta2]
distribution = logit_normal
min = 0.9
mean = 0.99999
max = 0.99999
scale = auto

[sweep.train.adam_eps]
distribution = log_normal
min = 1e-14
mean = 4.848310365732972e-12
max = 1e-4
scale = auto

[sweep.train.bptt_horizon]
distribution = uniform_pow2
min = 16
max = 64
mean = 64
scale = auto

[sweep.train.clip_coef]
distribution = uniform
min = 0.2
max = 0.7
mean = 0.3402139435986118
scale = auto

[sweep.train.ent_coef]
distribution = log_normal
min = 0.00001
mean = 0.030000000000000013
max = 0.03
scale = auto

[sweep.train.gae_lambda]
distribution = logit_normal
min = 0.6
mean = 0.9850334966277443
max = 0.995
scale = auto

[sweep.train.gamma]
distribution = logit_normal
min = 0.8
mean = 0.9993197059145731
max = 0.9999
scale = auto

[sweep.train.learning_rate]
distribution = log_normal
min = 0.00001
mean = 0.024999999999999994
max = 0.025
scale = auto

[sweep.train.max_grad_norm]
distribution = uniform
min = 0.0
mean = 4.488781435328298
max = 5.0
scale = auto

#[sweep.train.minibatch_size]
#distribution = uniform_pow2
#min = 8192
#max = 65536
#mean = 32768
#scale = auto

[sweep.train.prio_alpha]
distribution = logit_normal
min = 0.95
mean = 0.981927524144426
max = 0.99
scale = auto

[sweep.train.prio_beta0]
distribution = logit_normal
min = 0.1
mean = 0.09999999999999998
max = 0.99
scale = auto

[sweep.train.vf_clip_coef]
distribution = uniform
min = 0.3
max = 1.0
mean = 0.3
scale = auto

[sweep.train.vf_coef]
distribution = uniform
min = 4.0
max = 5.0
mean = 4.865415765982929
scale = auto

[sweep.train.vtrace_c_clip]
distribution = uniform
min = 2.0
max = 3.0
mean = 2.6829701985053878
scale = auto

[sweep.train.vtrace_rho_clip]
distribution = uniform
min = 1.0
max = 3.0
mean = 2.1589447317754478
scale = auto
