[base]
package = ocean
env_name = puffer_artymulti
policy_name = Policy
rnn_name = Recurrent

[vec]
num_envs = 1

[env]
num_envs = 1024
debug = 0

dist_fade = 0.15
frameskip = 1
miss_penalty = -0.1
max_reward_dist = 8.5
max_dist0 = 150
out_bounds_penalty = -0.1
turn_penalty = -0.03
turn_penalty_delay = 64
turn_penalty_ramp = 0.023
rng = 7

[policy]
hidden_size = 128

[rnn]
input_size = 128
hidden_size = 128

[train]
adam_beta1 = 0.4999999999999999
adam_beta2 = 0.99999
adam_eps = 4.822365784248077e-14
batch_size = 65536
bptt_horizon = 32
clip_coef = 0.7336770411958053
ent_coef = 0.02545103137261662
gae_lambda = 0.9983777353289575
gamma = 0.9619517324365382
learning_rate = 0.07485049804941932
max_grad_norm = 2.7541813812581166
#max_minibatch_size = 32768
#min_minibatch_size = 32768
minibatch_size = 16384 #16384 32768
prio_alpha = 0.9534492702799002
prio_beta0 = 0.9859434151055835
total_timesteps = 50_000_000
vf_clip_coef = 0.1
vf_coef = 0.5113428913980356
vtrace_c_clip = 3.807321800331179
vtrace_rho_clip = 5

[sweep]
method = Protein
metric = acc1000
goal = maximize
downsample = 10

#[sweep.train.total_timesteps]
#distribution = log_normal
#min = 90_000_000
#max = 100_000_000
#mean = 90_500_000
#scale = auto

#[sweep.train.learning_rate]
#distribution = log_normal
#min = 0.05
#mean = 0.065
#max = 0.08
#scale = 0.5

#[sweep.env.frameskip]
#distribution = categorical
#values = 1, 2, 4, 8

[sweep.env.dist_fade]
distribution = uniform
min = 0.1
max = 0.5
mean = 0.1
scale = auto

[sweep.env.max_dist0]
distribution = uniform
min = 25.0
max = 300.0
mean = 273.5175077308306
scale = auto

[sweep.env.max_reward_dist]
distribution = uniform
min = 5
max = 20
mean = 5.37848961547383
scale = auto

[sweep.env.miss_penalty]
distribution = uniform
min = -0.1
max = -0.001
mean = -0.001
scale = auto

[sweep.env.turn_penalty]
distribution = uniform
min = -0.1
max = -0.01
mean = -0.05402322836492127
scale = auto

[sweep.env.turn_penalty_delay]
distribution = uniform
min = 25
max = 75
mean = 50
scale = auto

[sweep.env.turn_penalty_ramp]
distribution = uniform
min = 0.01
max = 0.05
mean = 0.023561316583863783
scale = auto
