[base]
package = ocean
env_name = puffer_artymulti
policy_name = Policy
rnn_name = Recurrent

[vec]
num_envs = 1

[env]
num_envs = 1024
debug = 0

dist_fade = 0.15
frameskip = 1
miss_penalty = -0.1
max_reward_dist = 8.5
max_dist0 = 150
out_bounds_penalty = -0.1
turn_penalty = -0.03
turn_penalty_delay = 64
turn_penalty_ramp = 0.023
rng = 7

[policy]
hidden_size = 128

[rnn]
input_size = 128
hidden_size = 128

[train]
adam_beta1 = 0.9603485277769915
adam_beta2 = 0.9676992387435311
adam_eps = 9.4852806860935e-08
batch_size = 65536
bptt_horizon = 64
clip_coef = 0.048815198297704664
ent_coef = 0.049999999999999996
gae_lambda = 0.95
gamma = 0.9840496436204362
learning_rate = 0.005
max_grad_norm = 2.589981415830053
#max_minibatch_size = 32768
#min_minibatch_size = 32768
minibatch_size = 2048 #16384 32768
prio_alpha = 0.8573365561813164
prio_beta0 = 0.9145256572446854
total_timesteps = 50_000_000
vf_clip_coef = 0.1921803059597499
vf_coef = 0.8111721600187421
vtrace_c_clip = 2.13335526866267
vtrace_rho_clip = 2.0368704261583224

[sweep]
method = Protein
metric = acc1000
goal = maximize
downsample = 10

#[sweep.train.total_timesteps]
#distribution = log_normal
#min = 90_000_000
#max = 100_000_000
#mean = 90_500_000
#scale = auto

[sweep.train.learning_rate]
distribution = log_normal
min = 0.05
mean = 0.065
max = 0.08
scale = 0.5

#[sweep.env.frameskip]
#distribution = categorical
#values = 1, 2, 4, 8

#[sweep.env.max_dist0]
#distribution = uniform
#min = 25.0
#max = 300.0
#mean = 100.0
#scale = auto

#[sweep.env.dist_fade]
#distribution = uniform
#min = 0.01
#max = 1.0
#mean = 0.36
#scale = auto

#[sweep.env.max_reward_dist]
#distribution = uniform
#min = 5
#max = 50
#mean = 8.5
#scale = auto

#[sweep.env.turn_penalty]
#distribution = uniform
#min = -0.1
#max = -0.003
#mean = -0.003
#scale = auto

#[sweep.env.turn_penalty_delay]
#distribution = uniform
#min = 50
#max = 100
#mean = 64
#scale = auto

#[sweep.env.turn_penalty_ramp]
#distribution = uniform
#min = 0.01
#max = 0.05
#mean = 0.023
#scale = auto

#[sweep.env.miss_penalty]
#distribution = uniform
#min = -1.0
#max = -0.1
#mean = -0.1
#scale = auto

[sweep.train.vtrace_rho_clip]
distribution = uniform
min = 1.0
max = 5.0
mean = 1.5
scale = auto

[sweep.train.max_grad_norm]
distribution = uniform
min = 1.0
mean = 1.15
max = 5.0
scale = auto

[sweep.train.vf_coef]
distribution = uniform
min = 0.0
max = 1.0
mean = 1.0
scale = auto

[sweep.train.gae_lambda]
distribution = logit_normal
min = 0.95
mean = 0.96
max = 0.9995
scale = auto

[sweep.train.vtrace_c_clip]
distribution = uniform
min = 0.0
max = 4.0
mean = 1.3
scale = auto

#[sweep.train.minibatch_size]
#distribution = uniform_pow2
#min = 8192
#max = 32768
#mean = 16384
#scale = auto

[sweep.train.ent_coef]
distribution = log_normal
min = 0.00001
mean = 0.018
max = 0.05
scale = auto
