[base]
package = ocean
env_name = puffer_artymulti
policy_name = Policy
rnn_name = Recurrent

[vec]
num_envs = 1

[env]
num_envs = 1024

adj = 0.008340523121815914
dist_fade = 0.10813009001338028
frameskip = 1
max_dist0 = 136.33416713214024
max_reward_dist = 44.700659812685586
miss_penalty = -0.03448853813284214
out_bounds_penalty = -0.1
turn_penalty = -0.1
turn_penalty_delay = 57.64829992415082

[policy]
hidden_size = 128

[rnn]
input_size = 128
hidden_size = 128

[train]
adam_beta1 = 0.9452690775581809
adam_beta2 = 0.9990925021965602
adam_eps = 2.968390451936612e-11
batch_size = 65536
bptt_horizon = 64
clip_coef = 0.6547793760364998
ent_coef = 0.006885723413976504
gae_lambda = 0.9737987202698004
gamma = 0.9088574886201816
learning_rate = 0.01493961968126263
max_grad_norm = 2.7391802273363193
#max_minibatch_size = 32768
#min_minibatch_size = 32768
minibatch_size = 16384 #16384 32768
prio_alpha = 0.8001008888187823
prio_beta0 = 0.5809459552221135
total_timesteps = 100_000_000
vf_clip_coef = 4.235250757052023
vf_coef = 4.457567150171894
vtrace_c_clip = 2.178830704503352
vtrace_rho_clip = 4.839498327527892

[sweep]
method = Protein
metric = score
goal = maximize
downsample = 10

#[sweep.train.total_timesteps]
#distribution = log_normal
#min = 90_000_000
#max = 100_000_000
#mean = 90_500_000
#scale = auto

#[sweep.train.learning_rate]
#distribution = log_normal
#min = 0.05
#mean = 0.065
#max = 0.08
#scale = 0.5

#[sweep.env.frameskip]
#distribution = categorical
#values = 1, 2, 4, 8

[sweep.env.adj]
distribution = uniform
min = 0.005
max = 0.05
mean = 0.025
scale = auto

[sweep.env.dist_fade]
distribution = uniform
min = 0.1
max = 0.5
mean = 0.1
scale = auto

[sweep.env.max_dist0]
distribution = uniform
min = 100.0
max = 300.0
mean = 275
scale = auto

[sweep.env.max_reward_dist]
distribution = uniform
min = 15
max = 50
mean = 25
scale = auto

[sweep.env.miss_penalty]
distribution = uniform
min = -0.1
max = -0.001
mean = -0.04
scale = auto

[sweep.env.turn_penalty]
distribution = uniform
min = -0.1
max = -0.01
mean = -0.08
scale = auto

[sweep.env.turn_penalty_delay]
distribution = uniform
min = 25
max = 100
mean = 65
scale = auto
