[base]
package = ocean
env_name = puffer_boids 
; policy_name = Boids
policy_name = Policy
rnn_name = Recurrent
; rnn_name = None

[env]
num_envs = 64
num_boids = 64
margin_turn_factor = 0.0
cohesion_factor = 0.0
seperation_factor = 1.0
alignment_factor = 0.0

[vec]
num_workers = 2
num_envs = 2
batch_size = auto

[train]
; total_timesteps = 150_000_000
total_timesteps = 50_000_000
gamma = 0.95
learning_rate = 0.025
minibatch_size = 16384