# Inspired from squared.ini

[base]
package = ocean
env_name = puffer_flappy_bird_mini
policy_name = Policy
rnn_name = Recurrent

[vec]
num_envs = 12
num_workers = 12

[env]
num_envs = 512


[train]
total_timesteps = 10_000_000
gamma = 0.95
learning_rate = 0.05
minibatch_size = 32768
device = mps
