[base]
package = ocean
env_name = puffer_froggy
policy_name = Policy
rnn_name = Recurrent

[env]
num_envs = 1024
; MAX_MAP_WIDTH 50
; MAX_MAP_HEIGHT 25
width = 50
height = 25
episode_length = 500

[vec]
num_envs = 4

[train]
adam_beta1 = 0.4999999999999999
adam_beta2 = 0.9999634443782168
adam_eps = 0.00000001129702733166
anneal_lr = True
batch_size = auto
bptt_horizon = 64
checkpoint_interval = 200
clip_coef = 0.4402948160236574
compile = False
compile_fullgraph = True
compile_mode = max-autotune-no-cudagraphs
cpu_offload = False
data_dir = experiments
device = cuda
ent_coef = 0.20000000000000004
gae_lambda = 0.9910692670389832
gamma = 0.8023260815026797
learning_rate = 0.1
max_grad_norm = 1.6417573080756684
max_minibatch_size = 32768
minibatch_size = 32768
name = leanke
optimizer = muon
precision = float32
prio_alpha = 0.8165988326726807
prio_beta0 = 0.9036752309658332
project = puffer
seed = 42
torch_deterministic = True
total_timesteps = 49999999.99999989
update_epochs = 1
use_rnn = True
vf_clip_coef = 0.1
vf_coef = 0.8649461801762395
vtrace_c_clip = 2.550798689881474
vtrace_rho_clip = 2.0697878060200265

[sweep]
method = Protein 
metric = episode_return
goal = maximize
downsample = 10

[sweep.train.total_timesteps]
distribution = log_normal
min = 5e7
max = 1e10
mean = 1e8
scale = time

[sweep.train.bptt_horizon]
distribution = uniform_pow2
min = 16
max = 64
mean = 64
scale = auto

[sweep.train.minibatch_size]
distribution = uniform_pow2
min = 8192
max = 65536
mean = 32768
scale = auto

[sweep.train.learning_rate]
distribution = log_normal
min = 0.00001
mean = 0.01
max = 0.1
scale = 0.5

[sweep.train.ent_coef]
distribution = log_normal
min = 0.00001
mean = 0.01
max = 0.2
scale = auto

[sweep.train.gamma]
distribution = logit_normal
min = 0.8
mean = 0.98
max = 0.9999
scale = auto

[sweep.train.gae_lambda]
distribution = logit_normal
min = 0.6
mean = 0.95
max = 0.995
scale = auto

[sweep.train.vtrace_rho_clip]
distribution = uniform
min = 0.0
max = 5.0
mean = 1.0
scale = auto

[sweep.train.vtrace_c_clip]
distribution = uniform
min = 0.0
max = 5.0
mean = 1.0
scale = auto

[sweep.train.clip_coef]
distribution = uniform
min = 0.01
max = 1.0
mean = 0.2
scale = auto

[sweep.train.vf_clip_coef]
distribution = uniform
min = 0.1
max = 5.0
mean = 0.2
scale = auto

[sweep.train.vf_coef]
distribution = uniform
min = 0.0
max = 5.0
mean = 2.0
scale = auto

[sweep.train.max_grad_norm]
distribution = uniform
min = 0.0
mean = 1.0
max = 5.0
scale = auto

[sweep.train.adam_beta1]
distribution = logit_normal
min = 0.5
mean = 0.9
max = 0.999
scale = auto

[sweep.train.adam_beta2]
distribution = logit_normal
min = 0.9
mean = 0.999
max = 0.99999
scale = auto

[sweep.train.adam_eps]
distribution = log_normal
min = 1e-14
mean = 1e-8
max = 1e-4
scale = auto

[sweep.train.prio_alpha]
distribution = logit_normal
min = 0.1
mean = 0.85
max = 0.99
scale = auto

[sweep.train.prio_beta0]
distribution = logit_normal
min = 0.1
mean = 0.85
max = 0.99
scale = auto
