[base]
package = ocean
env_name = puffer_nonogram
policy_name = Nonogram
; policy_name = Policy
rnn_name = Recurrent

[env]
num_envs = 4096
min_size = 4
max_size = 8
easy_learn = 1

[sweep]
metric = score

[train]
; Hyperparameters from wandb config
name = pufferai
seed = 42
gamma = 0.99965
device = cuda
compile = False
project = ablations
use_rnn = True
vf_coef = 2.365
adam_eps = 1.566e-10
data_dir = experiments
ent_coef = 0.01554
anneal_lr = True
clip_coef = 0.1267
optimizer = muon
precision = float32
adam_beta1 = 0.7912
adam_beta2 = 0.999949
batch_size = auto
gae_lambda = 0.9007
prio_alpha = 0.7441
prio_beta0 = 0.7365
cpu_offload = False
bptt_horizon = 64
compile_mode = max-autotune-no-cudagraphs
vf_clip_coef = 1.598
learning_rate = 0.007103
max_grad_norm = 1.275
update_epochs = 1
vtrace_c_clip = 0.8692
minibatch_size = 32768
total_timesteps = 2e10
vtrace_rho_clip = 0.9074
compile_fullgraph = True
max_minibatch_size = 32768
checkpoint_interval = 200
torch_deterministic = True

; PREVIOUS RUN: Run ID 3k4cpz3ts3keprggvyldpo0bzpo2djsc
; total_timesteps = 1e10
; minibatch_size = 65536
; use_rnn = True
; update_epochs = 1
; bptt_horizon = 64
; gae_lambda = 0.9860112307817481
; gamma = 0.9955237802885055
; clip_coef = 0.3339182687952462
; vf_coef = 1.3604733057894562
; vf_clip_coef = 0.1
; ent_coef = 0.01267345559258322
; max_grad_norm = 0.7481994494317118
; learning_rate = 0.0071601604548789605
; adam_eps = 2.1466958248623007e-10
; adam_beta1 = 0.9600776540257598
; adam_beta2 = 0.9987918405974582
; anneal_lr = True
; optimizer = muon
; prio_alpha = 0.9248668653880601
; prio_beta0 = 0.9583638692801064
; vtrace_c_clip = 2.931704492528996
; vtrace_rho_clip = 1.2830763533710652

; PREVIOUS RUN: puffer_sweep_simple_policy
; total_timesteps = 1e10
; minibatch_size = 16384
; use_rnn = True
; update_epochs = 1
; bptt_horizon = 64
; gae_lambda = 0.9698
; gamma = 0.9979
; clip_coef = 0.1896
; vf_coef = 1.4565
; vf_clip_coef = 0.2296
; ent_coef = 0.01257
; max_grad_norm = 0.4804
; learning_rate = 0.06449
; adam_eps = 4.577e-10
; adam_beta1 = 0.8184
; adam_beta2 = 0.9996
; anneal_lr = True
; optimizer = muon
; prio_alpha = 0.8445
; prio_beta0 = 0.9498
; vtrace_c_clip = 3.5953
; vtrace_rho_clip = 2.2273

; PREVIOUS RUN: puffer_sweep_black_white_actions
; total_timesteps = 1e10
; minibatch_size = 32768
; use_rnn = True
; update_epochs = 1
; bptt_horizon = 64
; gae_lambda = 0.8645
; gamma = 0.9991
; clip_coef = 0.3043
; vf_coef = 2.1905
; vf_clip_coef = 3.1475
; ent_coef = 0.002274
; max_grad_norm = 1.0202
; learning_rate = 0.007169
; adam_eps = 6.036e-11
; adam_beta1 = 0.9366
; adam_beta2 = 0.9985
; anneal_lr = True
; optimizer = muon
; prio_alpha = 0.8741
; prio_beta0 = 0.7869
; vtrace_c_clip = 1.6859
; vtrace_rho_clip = 1.5254
; total_timesteps = 10_000_000_000
; minibatch_size = 32768
; use_rnn = True
; update_epochs = 1
; bptt_horizon = 64
; gae_lambda = 0.6
; gamma = 0.9999
; clip_coef = 0.01
; vf_coef = 4.453
; vf_clip_coef = 0.1
; ent_coef = 0.001160
; max_grad_norm = 1.071
; learning_rate = 0.003555
; adam_eps = 1.675e-14
; adam_beta1 = 0.9817
; adam_beta2 = 0.9052
; anneal_lr = True
; optimizer = muon
; compile = False
; precision = float32
; torch_deterministic = True
; checkpoint_interval = 200
; prio_alpha = 0.99
; prio_beta0 = 0.855
; vtrace_c_clip = 0.7794
; vtrace_rho_clip = 0.8655
