[base]
package = ocean
env_name = puffer_nonogram
policy_name = Policy
rnn_name = Recurrent

[env]
num_envs = 4096
min_size = 4
max_size = 8

[train]
total_timesteps = 2_000_000_000
minibatch_size = 65536
use_rnn = True
; update_epochs = 1
; bptt_horizon = 64
; gae_lambda = 0.933
; clip_coef = 0.405
; vf_coef = 1.74
; vf_clip_coef = 0.804
; ent_coef = 0.00048
; max_grad_norm = 2.84
; adam_eps = 1.47e-8
; adam_beta1 = 0.738
; adam_beta2 = 0.999987
; anneal_lr = True
; use_rnn = True
; optimizer = muon
; compile = False
; precision = float32
; torch_deterministic = True
; checkpoint_interval = 200
