[base]
package = ocean
env_name = puffer_tower_climb
policy_name = TowerClimb
rnn_name = Recurrent

[policy]
hidden_size = 256

[rnn]
hidden_size = 256
num_layers = 1

[vec]
num_envs = 4

[env]
num_envs = 1024
reward_climb_row = 0.16
reward_fall_row = -0.13
reward_illegal_move = -0.005
reward_move_block = 0.035

[train]
# https://wandb.ai/kywch/pufferlib/runs/b8ym2mvu/overview
total_timesteps = 600_000_000
anneal_lr = True
min_lr_ratio = 0.1
batch_size = auto
bptt_horizon = 64
minibatch_size = 65536

clip_coef = 0.6
ent_coef = 0.08
gae_lambda = 0.6
gamma = 0.95
vf_clip_coef = 5.0
vf_coef = 5.0

learning_rate = 0.023
max_grad_norm = 5.0

adam_beta1 = 0.81
adam_beta2 = 0.95
adam_eps = 1.0e-8
prio_alpha = 0.99
prio_beta0 = 0.99
vtrace_c_clip = 3.7
vtrace_rho_clip = 3.8

[sweep]
metric = perf
metric_distribution = percentile

# configs for targeted sweep. Comment these out for broad sweep
; downsample = 1
; sweep_only = reward_climb_row, reward_fall_row, reward_illegal_move, reward_move_block, learning_rate, adam_beta1, adam_beta2, adam_eps, vtrace_c_clip, vtrace_rho_clip

[sweep.train.total_timesteps]
distribution = uniform
min = 100_000_000
max = 2_000_000_000
scale = 0.5

[sweep.env.reward_climb_row]
distribution = uniform
min = 0.0
max = 1.0
scale = auto

[sweep.env.reward_fall_row]
distribution = uniform
min = -1.0
max = 0.0
scale = auto

[sweep.env.reward_illegal_move]
distribution = uniform
min = -1e-2
max = -1e-4
scale = auto

[sweep.env.reward_move_block]
distribution = uniform
min = 0.0
max = 1.0
scale = auto
