[base]
package = atari

env_name = atari_adventure atari_air_raid atari_alien atari_amidar atari_assault atari_asterix atari_asteroids atari_atlantis2 atari_atlantis atari_backgammon atari_bank_heist atari_basic_math atari_battle_zone atari_beam_rider atari_berzerk atari_blackjack atari_bowling atari_boxing atari_breakout atari_carnival atari_casino atari_centipede atari_chopper_command atari_combat atari_crazy_climber atari_crossbow atari_darkchambers atari_defender atari_demon_attack atari_donkey_kong atari_double_dunk atari_earthworld atari_elevator_action atari_enduro atari_entombed atari_et atari_fishing_derby atari_flag_capture atari_freeway atari_frogger atari_frostbite atari_galaxian atari_gopher atari_gravitar atari_hangman atari_haunted_house atari_hero atari_human_cannonball atari_ice_hockey atari_jamesbond atari_journey_escape atari_joust atari_kaboom atari_kangaroo atari_keystone_kapers atari_king_kong atari_klax atari_koolaid atari_krull atari_kung_fu_master atari_laser_gates atari_lost_luggage atari_mario_bros atari_maze_craze atari_miniature_golf atari_montezuma_revenge atari_mr_do atari_ms_pacman atari_name_this_game atari_othello atari_pacman atari_phoenix atari_pitfall2 atari_pitfall atari_pong atari_pooyan atari_private_eye atari_qbert atari_riverraid atari_road_runner atari_robotank atari_seaquest atari_sir_lancelot atari_skiing atari_solaris atari_space_invaders atari_space_war atari_star_gunner atari_superman atari_surround atari_tennis atari_tetris atari_tic_tac_toe_3d atari_time_pilot atari_trondead atari_turmoil atari_tutankham atari_up_n_down atari_venture atari_video_checkers atari_video_chess atari_video_cube atari_video_pinball atari_warlords atari_wizard_of_wor atari_word_zapper atari_yars_revenge atari_zaxxon

policy_name = Policy
rnn_name = Recurrent

[vec]
num_envs = 128
num_workers = 16
batch_size = 64

[train]
batch_size = 8192
minibatch_size = 2048
update_epochs = 1
horizon = 64
total_timesteps = 10_000_000
anneal_lr = False
use_rnn = False

[env]
frameskip = 1
repeat_action_probability = 0.0

[sweep.parameters.env.parameters.frameskip]
distribution = uniform
min = 1
max = 10

#[sweep.parameters.env.parameters.repeat_action_probability]
#distribution = uniform
#min = 0
#max = 1
 
[sweep.parameters.train.parameters.total_timesteps]
distribution = uniform
min = 5_000_000
max = 200_000_000

[sweep.parameters.train.parameters.batch_size]
distribution = uniform
min = 16384
max = 65536

[sweep.parameters.train.parameters.minibatch_size]
distribution = uniform
min = 512
max = 8192
